# Generated by Django 4.2.3 on 2023-08-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mymap", "0002_buildingsm"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="buildingsm",
            table="mymap_buildingsm",
        ),
    ]
